include: package:lints/recommended.yaml

linter:
  rules:
    annotate_overrides: false
    overridden_fields: false
    file_names: false
    non_constant_identifier_names: false
    constant_identifier_names: false
    