name: rec
description: Rec Barcelona app.
publish_to: 'none' 
version: 2.0.0+7

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  qr_code_scanner: 
  flutter_secure_storage: 3.3.3
  flutter_spinkit: ^4.1.2
  flutter_easyloading: ^2.2.2
  flutter_speed_dial: ^2.1.1
  contacts_service: ^0.4.6
  country_code_picker: ^1.7.0
  cupertino_icons: ^1.0.0
  google_maps_flutter: ^2.0.3
  qr_flutter: ^3.1.0
  http: ^0.12.0+4
  http_interceptor: ^0.3.3
  intl: ^0.17.0
  package_info: ^0.4.3+4
  permission_handler:
  provider: ^4.3.3
  sentry_flutter: ^4.0.4
  share: ^0.6.5+4
  timeago: ^2.0.26
  url_launcher: ^5.7.10
  modal_bottom_sheet: ^1.0.0+1
  webview_flutter: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.15.7
  pedantic: ^1.9.2
  image_test_utils: ^1.0.0
  flutter_launcher_icons: "^0.8.1"
  draggable_bottom_sheet: ^0.1.2


flutter_icons:    
  android: "launcher_icon"
  ios: true    
  image_path: "assets/logo.png"

flutter:
   assets:
     - assets/userIcon.png
     - assets/avatar.png
     - assets/avatar-bw.png
     - assets/organization-bw.png
     - assets/organization.png
     - assets/BolasRec.PNG
     - assets/logo.png
     - assets/imagenUsuarioPredeterminada.jpg
     - assets/aj-bcn.jpg
     - assets/login-header.jpg
     - assets/marcador.png
     - assets/recharge-ok.png
     - assets/recharge-ko.png
     - assets/marker.svg
     - assets/credit-cards/visa.png
     - assets/credit-cards/mastercard.png
     - i18n/ca.json
     - i18n/en.json
     - i18n/es.json
   uses-material-design: true