name: rec
description: Rec Barcelona app.
publish_to: 'none'
version: 2.0.1+19

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^4.2.0
  flutter_spinkit: ^5.0.0 
  flutter_easyloading: ^3.0.0
  flutter_speed_dial: ^3.0.5
  flutter_svg: ^0.22.0
  contacts_service: ^0.4.6
  country_code_picker: ^2.0.1
  cupertino_icons: ^1.0.0
  geocoding: ^2.0.0
  google_maps_flutter: ^2.0.6
  qr_flutter: ^3.1.0
  qr_code_scanner: ^0.4.0
  http: ^0.13.3
  http_interceptor: ^0.4.1
  intl: ^0.17.0
  modal_bottom_sheet: ^2.0.0
  package_info: ^2.0.1
  permission_handler: ^8.0.0+2
  provider: ^5.0.0
  sentry_flutter: ^5.0.0
  share: ^2.0.2
  shared_preferences: ^2.0.6
  timeago: ^2.0.26
  url_launcher: ^6.0.4
  webview_flutter: ^1.0.7
  dio: ^4.0.0
  image_picker: ^0.8.0+1
  path: ^1.8.0
  path_provider: ^2.0.2
  draggable_bottom_sheet: ^0.1.2
  pinput: ^1.2.0
  location: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.15.7
  pedantic: ^1.9.2
  image_test_utils: ^1.0.0
  flutter_launcher_icons: ^0.9.0

flutter_icons:    
  android: "launcher_icon"
  ios: true    
  image_path: "assets/logo.jpg"

flutter:
  assets:
    - assets/
    - assets/credit-cards/
    - assets/custom-icons/
    - i18n/ca.json
    - i18n/en.json
    - i18n/es.json
  uses-material-design: true