name: rec
description: Rec Barcelona app.
publish_to: 'none' 
version: 1.0.0+2

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: 3.3.3
  package_info: ^0.4.3+4
  cupertino_icons: ^1.0.0
  http: ^0.12.0+4
  provider: ^4.3.3
  flutter_spinkit: ^4.1.2
  sentry_flutter: ^4.0.4
  pinput: ^0.2.0
  pin_code_fields: ^6.1.0
  http_interceptor: ^0.3.3
  url_launcher: ^5.7.5
  country_code_picker: ^1.7.0
  intl: ^0.17.0
  flutter_speed_dial: ^2.1.1
  timeago: ^2.0.26
  google_maps_flutter: ^2.0.3
  flutter_easyloading: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.15.7
  pedantic: ^1.9.2
  image_test_utils: ^1.0.0
  flutter_launcher_icons: "^0.8.1"

flutter_icons:    
  android: "launcher_icon"
  ios: true    
  image_path: "assets/logo.png"

flutter:
   assets:
     - assets/userIcon.png
     - assets/avatar.png
     - assets/avatar-bw.png
     - assets/organization-bw.png
     - assets/organization.png
     - assets/BolasRec.PNG
     - assets/logo.png
     - assets/imagenUsuarioPredeterminada.jpg
     - assets/aj-bcn.jpg
     - assets/login-header.jpg
     - assets/marcador.png
     - i18n/ca.json
     - i18n/en.json
     - i18n/es.json
   uses-material-design: true