name: rec
description: Rec Barcelona app.
publish_to: 'none'
version: 2.4.1+103

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  flutter_spinkit: ^5.1.0 
  flutter_easyloading: ^3.0.5
  flutter_speed_dial: ^4.6.6
  flutter_dotenv: ^5.0.2
  flutter_svg: ^1.1.5
  rec_api_dart: ^1.4.0-alpha.16
  contacts_service: ^0.6.3
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.4
  dio: ^4.0.4
  geocoding: ^2.0.1
  google_maps_flutter: ^2.1.6
  qr_flutter: ^4.0.0
  mobile_scanner: ^2.0.0
  http: ^0.13.4
  http_interceptor: ^1.0.2
  intl: ^0.17.0
  package_info: ^2.0.2
  permission_handler: ^8.3.0
  provider: ^6.0.1
  sentry_flutter: ^6.9.1
  share: ^2.0.4
  shared_preferences: ^2.0.9
  timeago: ^3.1.0
  url_launcher: ^6.1.2
  webview_flutter: ^3.0.4
  image_picker: ^0.8.4+4 
  path: ^1.8.0
  path_provider: ^2.0.9
  pinput: ^2.2.9
  location: ^4.4.0
  collection: ^1.15.0-nullsafety.4
  modal_bottom_sheet: ^2.0.1
  styled_text: ^5.1.0
  cached_network_image: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.17.10 
  lints: ^1.0.1
  flutter_launcher_icons: ^0.9.3
  faker: ^2.0.0
  mockito: ^5.0.16
  dart_code_metrics: ^4.15.2

flutter:
  assets:
    - assets/
    - assets/current/
    - assets/current/banners/
    - assets/current/brand/
    - assets/current/cards/
    - assets/current/custom-icons/
    - assets/current/langs/
    - assets/current/markers/
    - assets/current/recharge/
    - assets/current/i18n/
    - env/
  uses-material-design: true